// Mocks generated by Mockito 5.4.4 from annotations
// in coffeespace_agentic_feed/test/features/feed/presentation/providers/replies_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:coffeespace_agentic_feed/core/cache/cache_manager.dart' as _i8;
import 'package:coffeespace_agentic_feed/core/network/api_client.dart' as _i9;
import 'package:coffeespace_agentic_feed/core/network/models/feed_page.dart'
    as _i2;
import 'package:coffeespace_agentic_feed/features/feed/data/models/post.dart'
    as _i3;
import 'package:coffeespace_agentic_feed/features/feed/data/models/reply.dart'
    as _i4;
import 'package:coffeespace_agentic_feed/features/feed/data/repositories/feed_repository.dart'
    as _i5;
import 'package:dio/dio.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFeedPage_0 extends _i1.SmartFake implements _i2.FeedPage {
  _FakeFeedPage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePost_1 extends _i1.SmartFake implements _i3.Post {
  _FakePost_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReply_2 extends _i1.SmartFake implements _i4.Reply {
  _FakeReply_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FeedRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRepository extends _i1.Mock implements _i5.FeedRepository {
  MockFeedRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.FeedPage> getFeed({
    String? cursor,
    int? limit = 50,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeed,
          [],
          {
            #cursor: cursor,
            #limit: limit,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i2.FeedPage>.value(_FakeFeedPage_0(
          this,
          Invocation.method(
            #getFeed,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i2.FeedPage>);

  @override
  _i6.Future<_i3.Post> toggleLike({
    required String? postId,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLike,
          [],
          {
            #postId: postId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i3.Post>.value(_FakePost_1(
          this,
          Invocation.method(
            #toggleLike,
            [],
            {
              #postId: postId,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i3.Post>);

  @override
  _i6.Future<_i3.Post> toggleRepost({
    required String? postId,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleRepost,
          [],
          {
            #postId: postId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i3.Post>.value(_FakePost_1(
          this,
          Invocation.method(
            #toggleRepost,
            [],
            {
              #postId: postId,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i3.Post>);

  @override
  _i6.Future<List<_i4.Reply>> getReplies({
    required String? postId,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReplies,
          [],
          {
            #postId: postId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<List<_i4.Reply>>.value(<_i4.Reply>[]),
      ) as _i6.Future<List<_i4.Reply>>);

  @override
  _i6.Future<_i4.Reply> addReply({
    required String? postId,
    required String? content,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReply,
          [],
          {
            #postId: postId,
            #content: content,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i4.Reply>.value(_FakeReply_2(
          this,
          Invocation.method(
            #addReply,
            [],
            {
              #postId: postId,
              #content: content,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i4.Reply>);

  @override
  _i6.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [CacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheManager extends _i1.Mock implements _i8.CacheManager {
  MockCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  T? get<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as T?);

  @override
  T? getWithTTL<T>(
    String? key, {
    Duration? ttl,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getWithTTL,
        [key],
        {#ttl: ttl},
      )) as T?);

  @override
  _i6.Future<void> set<T>(
    String? key,
    T? value, {
    bool? withTTL = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            value,
          ],
          {#withTTL: withTTL},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  Iterable<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i9.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setFailureRate(double? rate) => super.noSuchMethod(
        Invocation.method(
          #setFailureRate,
          [rate],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i2.FeedPage> getFeed({
    String? cursor,
    int? limit = 50,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeed,
          [],
          {
            #cursor: cursor,
            #limit: limit,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i2.FeedPage>.value(_FakeFeedPage_0(
          this,
          Invocation.method(
            #getFeed,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i2.FeedPage>);

  @override
  _i6.Future<_i3.Post> toggleLike({
    required String? postId,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLike,
          [],
          {
            #postId: postId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i3.Post>.value(_FakePost_1(
          this,
          Invocation.method(
            #toggleLike,
            [],
            {
              #postId: postId,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i3.Post>);

  @override
  _i6.Future<_i3.Post> toggleRepost({
    required String? postId,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleRepost,
          [],
          {
            #postId: postId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i3.Post>.value(_FakePost_1(
          this,
          Invocation.method(
            #toggleRepost,
            [],
            {
              #postId: postId,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i3.Post>);

  @override
  _i6.Future<_i4.Reply> createReply({
    required String? postId,
    required String? content,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReply,
          [],
          {
            #postId: postId,
            #content: content,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<_i4.Reply>.value(_FakeReply_2(
          this,
          Invocation.method(
            #createReply,
            [],
            {
              #postId: postId,
              #content: content,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i6.Future<_i4.Reply>);

  @override
  _i6.Future<List<_i4.Reply>> getReplies({
    required String? postId,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReplies,
          [],
          {
            #postId: postId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i6.Future<List<_i4.Reply>>.value(<_i4.Reply>[]),
      ) as _i6.Future<List<_i4.Reply>>);
}
