// Mocks generated by Mockito 5.4.4 from annotations
// in coffeespace_agentic_feed/test/features/feed/data/repositories/feed_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:coffeespace_agentic_feed/core/cache/cache_manager.dart' as _i9;
import 'package:coffeespace_agentic_feed/core/metrics/metrics_collector.dart'
    as _i5;
import 'package:coffeespace_agentic_feed/core/network/api_client.dart' as _i6;
import 'package:coffeespace_agentic_feed/core/network/models/feed_page.dart'
    as _i2;
import 'package:coffeespace_agentic_feed/features/feed/data/models/post.dart'
    as _i3;
import 'package:coffeespace_agentic_feed/features/feed/data/models/reply.dart'
    as _i4;
import 'package:dio/dio.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFeedPage_0 extends _i1.SmartFake implements _i2.FeedPage {
  _FakeFeedPage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePost_1 extends _i1.SmartFake implements _i3.Post {
  _FakePost_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReply_2 extends _i1.SmartFake implements _i4.Reply {
  _FakeReply_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCacheMetrics_3 extends _i1.SmartFake implements _i5.CacheMetrics {
  _FakeCacheMetrics_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAPIMetrics_4 extends _i1.SmartFake implements _i5.APIMetrics {
  _FakeAPIMetrics_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOptimisticMetrics_5 extends _i1.SmartFake
    implements _i5.OptimisticMetrics {
  _FakeOptimisticMetrics_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserInteractionMetrics_6 extends _i1.SmartFake
    implements _i5.UserInteractionMetrics {
  _FakeUserInteractionMetrics_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLifecycleMetrics_7 extends _i1.SmartFake
    implements _i5.LifecycleMetrics {
  _FakeLifecycleMetrics_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnectivityMetrics_8 extends _i1.SmartFake
    implements _i5.ConnectivityMetrics {
  _FakeConnectivityMetrics_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeErrorMetrics_9 extends _i1.SmartFake implements _i5.ErrorMetrics {
  _FakeErrorMetrics_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i6.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void setFailureRate(double? rate) => super.noSuchMethod(
        Invocation.method(
          #setFailureRate,
          [rate],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.FeedPage> getFeed({
    String? cursor,
    int? limit = 50,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFeed,
          [],
          {
            #cursor: cursor,
            #limit: limit,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i2.FeedPage>.value(_FakeFeedPage_0(
          this,
          Invocation.method(
            #getFeed,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i2.FeedPage>);

  @override
  _i7.Future<_i3.Post> toggleLike({
    required String? postId,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLike,
          [],
          {
            #postId: postId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i3.Post>.value(_FakePost_1(
          this,
          Invocation.method(
            #toggleLike,
            [],
            {
              #postId: postId,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i3.Post>);

  @override
  _i7.Future<_i3.Post> toggleRepost({
    required String? postId,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleRepost,
          [],
          {
            #postId: postId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i3.Post>.value(_FakePost_1(
          this,
          Invocation.method(
            #toggleRepost,
            [],
            {
              #postId: postId,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i3.Post>);

  @override
  _i7.Future<_i4.Reply> createReply({
    required String? postId,
    required String? content,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createReply,
          [],
          {
            #postId: postId,
            #content: content,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<_i4.Reply>.value(_FakeReply_2(
          this,
          Invocation.method(
            #createReply,
            [],
            {
              #postId: postId,
              #content: content,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i7.Future<_i4.Reply>);

  @override
  _i7.Future<List<_i4.Reply>> getReplies({
    required String? postId,
    _i8.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReplies,
          [],
          {
            #postId: postId,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i7.Future<List<_i4.Reply>>.value(<_i4.Reply>[]),
      ) as _i7.Future<List<_i4.Reply>>);
}

/// A class which mocks [CacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheManager extends _i1.Mock implements _i9.CacheManager {
  MockCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  T? get<T>(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as T?);

  @override
  T? getWithTTL<T>(
    String? key, {
    Duration? ttl,
  }) =>
      (super.noSuchMethod(Invocation.method(
        #getWithTTL,
        [key],
        {#ttl: ttl},
      )) as T?);

  @override
  _i7.Future<void> set<T>(
    String? key,
    T? value, {
    bool? withTTL = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            key,
            value,
          ],
          {#withTTL: withTTL},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  Iterable<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>[],
      ) as Iterable<String>);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [MetricsCollector].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetricsCollector extends _i1.Mock implements _i5.MetricsCollector {
  MockMetricsCollector() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void trackCacheHit(String? key) => super.noSuchMethod(
        Invocation.method(
          #trackCacheHit,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackCacheMiss(String? key) => super.noSuchMethod(
        Invocation.method(
          #trackCacheMiss,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackAPICall(
    String? endpoint,
    bool? success,
    double? latencyMs,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #trackAPICall,
          [
            endpoint,
            success,
            latencyMs,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackOptimisticAction(
    String? action,
    bool? success,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #trackOptimisticAction,
          [
            action,
            success,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.CacheMetrics getCacheMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getCacheMetrics,
          [],
        ),
        returnValue: _FakeCacheMetrics_3(
          this,
          Invocation.method(
            #getCacheMetrics,
            [],
          ),
        ),
      ) as _i5.CacheMetrics);

  @override
  _i5.APIMetrics getAPIMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getAPIMetrics,
          [],
        ),
        returnValue: _FakeAPIMetrics_4(
          this,
          Invocation.method(
            #getAPIMetrics,
            [],
          ),
        ),
      ) as _i5.APIMetrics);

  @override
  _i5.OptimisticMetrics getOptimisticMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getOptimisticMetrics,
          [],
        ),
        returnValue: _FakeOptimisticMetrics_5(
          this,
          Invocation.method(
            #getOptimisticMetrics,
            [],
          ),
        ),
      ) as _i5.OptimisticMetrics);

  @override
  _i5.UserInteractionMetrics getUserInteractionMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getUserInteractionMetrics,
          [],
        ),
        returnValue: _FakeUserInteractionMetrics_6(
          this,
          Invocation.method(
            #getUserInteractionMetrics,
            [],
          ),
        ),
      ) as _i5.UserInteractionMetrics);

  @override
  _i5.LifecycleMetrics getLifecycleMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getLifecycleMetrics,
          [],
        ),
        returnValue: _FakeLifecycleMetrics_7(
          this,
          Invocation.method(
            #getLifecycleMetrics,
            [],
          ),
        ),
      ) as _i5.LifecycleMetrics);

  @override
  _i5.ConnectivityMetrics getConnectivityMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getConnectivityMetrics,
          [],
        ),
        returnValue: _FakeConnectivityMetrics_8(
          this,
          Invocation.method(
            #getConnectivityMetrics,
            [],
          ),
        ),
      ) as _i5.ConnectivityMetrics);

  @override
  _i5.ErrorMetrics getErrorMetrics() => (super.noSuchMethod(
        Invocation.method(
          #getErrorMetrics,
          [],
        ),
        returnValue: _FakeErrorMetrics_9(
          this,
          Invocation.method(
            #getErrorMetrics,
            [],
          ),
        ),
      ) as _i5.ErrorMetrics);

  @override
  void trackUserInteraction(
    String? type, {
    Map<String, dynamic>? parameters,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackUserInteraction,
          [type],
          {#parameters: parameters},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackScreenView(
    String? screenName, {
    Map<String, dynamic>? parameters,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackScreenView,
          [screenName],
          {#parameters: parameters},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackLifecycleEvent(
    String? event, {
    Map<String, dynamic>? metadata,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackLifecycleEvent,
          [event],
          {#metadata: metadata},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackConnectivityChange(
    bool? isOnline, {
    String? networkType,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackConnectivityChange,
          [isOnline],
          {#networkType: networkType},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackError(
    String? type,
    String? message, {
    Map<String, dynamic>? context,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #trackError,
          [
            type,
            message,
          ],
          {#context: context},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
